import os
from dotenv import load_dotenv
from app.services.gemini import get_embeddings
from pinecone import Pinecone
from langchain_pinecone import PineconeVectorStore
from langchain_core.documents import Document

load_dotenv()

def seed_pinecone():
    print("Connecting to Pinecone...")
    api_key = os.getenv("PINECONE_API_KEY")
    index_name = os.getenv("PINECONE_INDEX_NAME")
    
    if not api_key or not index_name:
        raise ValueError("Ensure PINECONE_API_KEY and PINECONE_INDEX_NAME are set in your environment variables.")

    pc = Pinecone(api_key=api_key)
    index = pc.Index(index_name)
    
    embeddings = get_embeddings()
    
    # Define corporate policy mock chunks
    sample_policies = [
        "Return & Refund Policy: Customers can return any device within 30 days of purchase for a full refund. The item must be in its original packaging. If the item arrived damaged or broken, the return shipping fees are completely covered by us, and a replacement will be sent out immediately upon request.",
        "Warranty Policy: All hardware electronics items sold include a 1-year limited warranty covering factory defects, hardware failures, and screen issues not caused by accidental drops or liquid damage.",
        "Shipping Policy: Standard shipping takes 3-5 business days. Express shipping takes 1-2 business days. Orders exceeding $100 are automatically eligible for free standard shipping globally.",
        "Support Escalation Policy: If a support ticket is generated by our engineering department, it is marked as 'Open' by default. Our internal customer success staff is strictly required to review and respond to all newly opened tickets within 24 hours."
    ]
    
    # Wrap texts into LangChain Document objects
    documents = [Document(page_content=text, metadata={"source": "company_handbook"}) for text in sample_policies]
    
    print(f"Generating embeddings and uploading {len(documents)} text chunks to Pinecone index '{index_name}'...")
    
    # This automatically runs embeddings and pushes to Pinecone
    PineconeVectorStore.from_documents(
        documents,
        embedding=embeddings,
        index_name=index_name
    )
    
    print("Successfully seeded Pinecone index context!")

if __name__ == "__main__":
    seed_pinecone()
